DONE

diff --git a/philo/Makefile b/philo/Makefile
--- a/philo/Makefile
+++ b/philo/Makefile
@@ -11,7 +11,7 @@ NOCOLOR = \033[0m
 
 # Compiler and Flags
 CC = cc
-CFLAGS = -Wall -Werror -Wextra -g -pthread -fsanitize=thread
+CFLAGS = -Wall -Werror -Wextra -g -pthread #-fsanitize=thread
 
 # Dependency Generation Flags
 # -MMD: Generates dependency files (.d) while compiling
@@ -24,11 +24,11 @@ DEPFLAGS = -MT $@ -MMD -MP -MF $(OBJ_DIR)/$*.d
 SRC_DIR = src
 OBJ_DIR = obj
 INC_DIR = include
-LIBFT_DIR = libft
-PRINTF_DIR = printf
+#LIBFT_DIR = libft
+#PRINTF_DIR = printf
 
 # Source files
-SRC_FILES =	src/utils.c src/utils1.c \
+SRC_FILES =	src/utils.c src/utils1.c src/ft_calloc.c \
 			src/initiate.c src/mutexes.c \
 			src/routine.c src/start.c \
 			src/time.c src/main.c src/solo_routine.c \
@@ -50,28 +50,42 @@ $(OBJ_DIR)/%.o: $(SRC_DIR)/%.c | $(OBJ_DIR)
 	@$(CC) $(DEPFLAGS) $(CFLAGS) -I$(INC_DIR) -c $< -o $@
 	@printf "$(CYAN)Compiled:$(NOCOLOR) %s\n" "$<"
 
-# Libraries (silent mode)
-$(LIBFT_DIR)/libft.a:
-	@make -C $(LIBFT_DIR) --no-print-directory >/dev/null 2>&1
+## Libraries (silent mode)
+#$(LIBFT_DIR)/libft.a:
+#	@make -C $(LIBFT_DIR) --no-print-directory >/dev/null 2>&1
 
-$(PRINTF_DIR)/libftprintf.a:
-	@make -C $(PRINTF_DIR) --no-print-directory >/dev/null 2>&1
+#$(PRINTF_DIR)/libftprintf.a:
+#	@make -C $(PRINTF_DIR) --no-print-directory >/dev/null 2>&1
 
-libs: $(LIBFT_DIR)/libft.a $(PRINTF_DIR)/libftprintf.a
+#libs: $(LIBFT_DIR)/libft.a $(PRINTF_DIR)/libftprintf.a
 
 # Final linking
-$(NAME): libs $(OBJ_FILES)
+$(NAME): $(OBJ_FILES) #libs (insert befre $(OBJ_FILES))
 	@if [ "$(OBJ_FILES)" != "" ] && [ "$(filter-out libs,$?)" != "" ]; then \
-		$(CC) $(CFLAGS) $(OBJ_FILES) $(LIBFT_DIR)/libft.a $(PRINTF_DIR)/libftprintf.a -o $@ && \
+		$(CC) $(CFLAGS) $(OBJ_FILES) -o $@ && \
 		printf "$(GREEN)✓ $(NAME) built successfully$(NOCOLOR)\n" || \
 		printf "$(RED)✗ Failed to build $(NAME)$(NOCOLOR)\n"; \
 	elif [ ! -f $(NAME) ]; then \
-		$(CC) $(CFLAGS) $(OBJ_FILES) $(LIBFT_DIR)/libft.a $(PRINTF_DIR)/libftprintf.a -o $@ && \
+		$(CC) $(CFLAGS) $(OBJ_FILES) -o $@ && \
 		printf "$(GREEN)✓ $(NAME) built successfully$(NOCOLOR)\n" || \
 		printf "$(RED)✗ Failed to build $(NAME)$(NOCOLOR)\n"; \
 	else \
 		printf "$(BLUE)Nothing to be done$(NOCOLOR)\n"; \
 	fi
+
+## Final linking
+#$(NAME): $(OBJ_FILES) #libs (insert befre $(OBJ_FILES))
+#	@if [ "$(OBJ_FILES)" != "" ] && [ "$(filter-out libs,$?)" != "" ]; then \
+#		$(CC) $(CFLAGS) $(OBJ_FILES) $(LIBFT_DIR)/libft.a $(PRINTF_DIR)/libftprintf.a -o $@ && \
+#		printf "$(GREEN)✓ $(NAME) built successfully$(NOCOLOR)\n" || \
+#		printf "$(RED)✗ Failed to build $(NAME)$(NOCOLOR)\n"; \
+#	elif [ ! -f $(NAME) ]; then \
+#		$(CC) $(CFLAGS) $(OBJ_FILES) $(LIBFT_DIR)/libft.a $(PRINTF_DIR)/libftprintf.a -o $@ && \
+#		printf "$(GREEN)✓ $(NAME) built successfully$(NOCOLOR)\n" || \
+#		printf "$(RED)✗ Failed to build $(NAME)$(NOCOLOR)\n"; \
+#	else \
+#		printf "$(BLUE)Nothing to be done$(NOCOLOR)\n"; \
+#	fi
 
 # Clean rules with precise messaging
 clean:
@@ -81,20 +95,21 @@ clean:
 	else \
 		printf "$(BLUE)✓ Object files were already removed$(NOCOLOR)\n"; \
 	fi
-	@make clean -C $(LIBFT_DIR) --no-print-directory >/dev/null 2>&1
-	@make clean -C $(PRINTF_DIR) --no-print-directory >/dev/null 2>&1
+
+## Clean rules with precise messaging
+#clean:
+#	@if [ -d "$(OBJ_DIR)" ]; then \
+#		rm -rf $(OBJ_DIR) >/dev/null 2>&1; \
+#		printf "$(BLUE)✓ Object files removed$(NOCOLOR)\n"; \
+#	else \
+#		printf "$(BLUE)✓ Object files were already removed$(NOCOLOR)\n"; \
+#	fi
+#	@make clean -C $(LIBFT_DIR) --no-print-directory >/dev/null 2>&1
+#	@make clean -C $(PRINTF_DIR) --no-print-directory >/dev/null 2>&1
 
 fclean: clean
 	@if [ -f "$(NAME)" ]; then \
 		rm -f $(NAME) >/dev/null 2>&1; \
-		rm_flag=1; \
-	fi; \
-	if [ -f "$(LIBFT_DIR)/libft.a" ]; then \
-		make fclean -C $(LIBFT_DIR) --no-print-directory >/dev/null 2>&1; \
-		rm_flag=1; \
-	fi; \
-	if [ -f "$(PRINTF_DIR)/libftprintf.a" ]; then \
-		make fclean -C $(PRINTF_DIR) --no-print-directory >/dev/null 2>&1; \
 		rm_flag=1; \
 	fi; \
 	if [ "$$rm_flag" = "1" ]; then \
@@ -102,6 +117,26 @@ fclean: clean
 	else \
 		printf "$(BLUE)✓ Everything was already removed$(NOCOLOR)\n"; \
 	fi
+
+
+#fclean: clean
+#	@if [ -f "$(NAME)" ]; then \
+#		rm -f $(NAME) >/dev/null 2>&1; \
+#		rm_flag=1; \
+#	fi; \
+#	if [ -f "$(LIBFT_DIR)/libft.a" ]; then \
+#		make fclean -C $(LIBFT_DIR) --no-print-directory >/dev/null 2>&1; \
+#		rm_flag=1; \
+#	fi; \
+#	if [ -f "$(PRINTF_DIR)/libftprintf.a" ]; then \
+#		make fclean -C $(PRINTF_DIR) --no-print-directory >/dev/null 2>&1; \
+#		rm_flag=1; \
+#	fi; \
+#	if [ "$$rm_flag" = "1" ]; then \
+#		printf "$(BLUE)✓ All files cleaned$(NOCOLOR)\n"; \
+#	else \
+#		printf "$(BLUE)✓ Everything was already removed$(NOCOLOR)\n"; \
+#	fi
 
 re: fclean all
 
